import { editor } from 'monaco-editor';

export default {
  base: 'vs-dark',
  inherit: true,
  rules: [
    {
      background: '211E1E',
      token: '',
    },
    {
      foreground: '555555',
      token: 'comment',
    },
    {
      foreground: '555555',
      token: 'comment.block',
    },
    {
      foreground: 'ad9361',
      token: 'string',
    },
    {
      foreground: 'cccccc',
      token: 'constant.numeric',
    },
    {
      foreground: 'a1a1ff',
      token: 'keyword',
    },
    {
      foreground: '2f006e',
      token: 'meta.preprocessor',
    },
    {
      fontStyle: 'bold',
      token: 'keyword.control.import',
    },
    {
      foreground: 'a1a1ff',
      token: 'support.function',
    },
    {
      foreground: '0000ff',
      token: 'declaration.function function-result',
    },
    {
      fontStyle: 'bold',
      token: 'declaration.function function-name',
    },
    {
      fontStyle: 'bold',
      token: 'declaration.function argument-name',
    },
    {
      foreground: '0000ff',
      token: 'declaration.function function-arg-type',
    },
    {
      fontStyle: 'italic',
      token: 'declaration.function function-argument',
    },
    {
      fontStyle: 'underline',
      token: 'declaration.class class-name',
    },
    {
      fontStyle: 'italic underline',
      token: 'declaration.class class-inheritance',
    },
    {
      foreground: 'fff9f9',
      background: 'ff0000',
      fontStyle: 'bold',
      token: 'invalid',
    },
    {
      background: 'ffd0d0',
      token: 'invalid.deprecated.trailing-whitespace',
    },
    {
      fontStyle: 'italic',
      token: 'declaration.section section-name',
    },
    {
      foreground: 'c10006',
      token: 'string.interpolation',
    },
    {
      foreground: '666666',
      token: 'string.regexp',
    },
    {
      foreground: 'c1c144',
      token: 'variable',
    },
    {
      foreground: '6782d3',
      token: 'constant',
    },
    {
      foreground: 'afa472',
      token: 'constant.character',
    },
    {
      foreground: 'de8e30',
      fontStyle: 'bold',
      token: 'constant.language',
    },
    {
      fontStyle: 'underline',
      token: 'embedded',
    },
    {
      foreground: '858ef4',
      token: 'keyword.markup.element-name',
    },
    {
      foreground: '9b456f',
      token: 'keyword.markup.attribute-name',
    },
    {
      foreground: '9b456f',
      token: 'meta.attribute-with-value',
    },
    {
      foreground: 'c82255',
      fontStyle: 'bold',
      token: 'keyword.exception',
    },
    {
      foreground: '47b8d6',
      token: 'keyword.operator',
    },
    {
      foreground: '6969fa',
      fontStyle: 'bold',
      token: 'keyword.control',
    },
    {
      foreground: '68685b',
      token: 'meta.tag.preprocessor.xml',
    },
    {
      foreground: '888888',
      token: 'meta.tag.sgml.doctype',
    },
    {
      fontStyle: 'italic',
      token: 'string.quoted.docinfo.doctype.DTD',
    },
    {
      foreground: '909090',
      token: 'comment.other.server-side-include.xhtml',
    },
    {
      foreground: '909090',
      token: 'comment.other.server-side-include.html',
    },
    {
      foreground: '858ef4',
      token: 'text.html declaration.tag',
    },
    {
      foreground: '858ef4',
      token: 'text.html meta.tag',
    },
    {
      foreground: '858ef4',
      token: 'text.html entity.name.tag.xhtml',
    },
    {
      foreground: '9b456f',
      token: 'keyword.markup.attribute-name',
    },
    {
      foreground: '777777',
      token: 'keyword.other.phpdoc.php',
    },
    {
      foreground: 'c82255',
      token: 'keyword.other.include.php',
    },
    {
      foreground: 'de8e20',
      fontStyle: 'bold',
      token: 'support.constant.core.php',
    },
    {
      foreground: 'de8e10',
      fontStyle: 'bold',
      token: 'support.constant.std.php',
    },
    {
      foreground: 'b72e1d',
      token: 'variable.other.global.php',
    },
    {
      foreground: '00ff00',
      token: 'variable.other.global.safer.php',
    },
    {
      foreground: 'bfa36d',
      token: 'string.quoted.single.php',
    },
    {
      foreground: '6969fa',
      token: 'keyword.storage.php',
    },
    {
      foreground: 'ad9361',
      token: 'string.quoted.double.php',
    },
    {
      foreground: 'ec9e00',
      token: 'entity.other.attribute-name.id.css',
    },
    {
      foreground: 'b8cd06',
      fontStyle: 'bold',
      token: 'entity.name.tag.css',
    },
    {
      foreground: 'edca06',
      token: 'entity.other.attribute-name.class.css',
    },
    {
      foreground: '2e759c',
      token: 'entity.other.attribute-name.pseudo-class.css',
    },
    {
      foreground: 'ffffff',
      background: 'ff0000',
      token: 'invalid.bad-comma.css',
    },
    {
      foreground: '9b2e4d',
      token: 'support.constant.property-value.css',
    },
    {
      foreground: 'e1c96b',
      token: 'support.type.property-name.css',
    },
    {
      foreground: '666633',
      token: 'constant.other.rgb-value.css',
    },
    {
      foreground: '666633',
      token: 'support.constant.font-name.css',
    },
    {
      foreground: '7171f3',
      token: 'support.constant.tm-language-def',
    },
    {
      foreground: '7171f3',
      token: 'support.constant.name.tm-language-def',
    },
    {
      foreground: '6969fa',
      token: 'keyword.other.unit.css',
    },
  ],
  colors: {
    focusBorder: '#FFFFFF00',
    'editorCursor.foreground': '#FFCC00',
    'editorRuler.foreground': '#4E5579',
    'scrollbar.shadow': '#292D3E00',
    'editorLink.activeForeground': '#A6ACCD',
    'selection.background': '#80CBC4',
    'progressBar.background': '#80CBC4',
    'textLink.foreground': '#80CBC4',
    'textLink.activeForeground': '#A6ACCD',
    'widget.shadow': '#00000030',
    'button.background': '#717CB450',
    'debugToolBar.background': '#292D3E',
    'pickerGroup.foreground': '#80CBC4',
    'inputOption.activeBackground': '#A6ACCD30',
    'inputOption.activeBorder': '#A6ACCD30',
    'editorLineNumber.foreground': '#3A3F58',
    'editorLineNumber.activeForeground': '#676E95',
    'editorBracketMatch.border': '#FFCC0050',
    'editorBracketMatch.background': '#292D3E',
    'editorWhitespace.foreground': '#A6ACCD40',
    'editorOverviewRuler.findMatchForeground': '#80CBC4',
    'editorOverviewRuler.border': '#292D3E',
    'editorOverviewRuler.errorForeground': '#FF537040',
    'editorOverviewRuler.infoForeground': '#82AAFF40',
    'editorOverviewRuler.warningForeground': '#FFCB6B40',
    'editorInfo.foreground': '#82AAFF70',
    'editorWarning.foreground': '#FFCB6B70',
    'editorError.foreground': '#FF537070',
    'editorHoverWidget.background': '#292D3E',
    'editorHoverWidget.border': '#FFFFFF10',
    'editorIndentGuide.background': '#4E557970',
    'editorIndentGuide.activeBackground': '#4E5579',
    'editorGroupHeader.tabsBackground': '#292D3E',
    'editorGroup.border': '#00000030',
    'editorGutter.modifiedBackground': '#82AAFF60',
    'editorGutter.addedBackground': '#C3E88D60',
    'editorGutter.deletedBackground': '#FF537060',
    'editor.background': '#292D3E',
    'editor.foreground': '#A6ACCD',
    'editor.lineHighlightBackground': '#00000050',
    'editor.selectionBackground': '#717CB450',
    'editor.selectionHighlightBackground': '#FFCC0020',
    'editor.findMatchBackground': '#000000',
    'editor.findMatchHighlightBackground': '#00000050',
    'editor.findMatchBorder': '#80CBC4',
    'editor.findMatchHighlightBorder': '#ffffff30',
    'tab.activeBorder': '#80CBC4',
    'tab.activeModifiedBorder': '#676E95',
    'tab.unfocusedActiveBorder': '#676E95',
    'tab.activeForeground': '#FFFFFF',
    'tab.inactiveForeground': '#676E95',
    'tab.inactiveBackground': '#292D3E',
    'tab.unfocusedActiveForeground': '#A6ACCD',
    'tab.border': '#292D3E',
    'statusBar.noFolderBackground': '#292D3E',
    'statusBar.border': '#292D3E60',
    'statusBar.background': '#292D3E',
    'statusBar.foreground': '#676E95',
    'statusBar.debuggingBackground': '#C792EA',
    'statusBar.debuggingForeground': '#ffffff',
    'statusBarItem.hoverBackground': '#676E9520',
    'statusBarItem.remoteForeground': '#000000',
    'statusBarItem.remoteBackground': '#80CBC4',
    'activityBar.background': '#292D3E',
    'activityBar.border': '#292D3E60',
    'activityBar.foreground': '#A6ACCD',
    'activityBarBadge.background': '#80CBC4',
    'activityBarBadge.foreground': '#000000',
    'titleBar.activeBackground': '#292D3E',
    'titleBar.activeForeground': '#A6ACCD',
    'titleBar.inactiveBackground': '#292D3E',
    'titleBar.inactiveForeground': '#676E95',
    'titleBar.border': '#292D3E60',
    'sideBar.background': '#292D3E',
    'sideBar.foreground': '#676E95',
    'sideBar.border': '#292D3E60',
    'sideBarTitle.foreground': '#A6ACCD',
    'sideBarSectionHeader.background': '#292D3E',
    'sideBarSectionHeader.border': '#292D3E60',
    'input.background': '#333747',
    'input.foreground': '#EEFFFF',
    'input.placeholderForeground': '#A6ACCD60',
    'input.border': '#FFFFFF10',
    'inputValidation.errorBorder': '#FF537050',
    'inputValidation.infoBorder': '#82AAFF50',
    'inputValidation.warningBorder': '#FFCB6B50',
    'dropdown.background': '#292D3E',
    'dropdown.border': '#FFFFFF10',
    'list.hoverForeground': '#FFFFFF',
    'list.hoverBackground': '#292D3E',
    'list.activeSelectionBackground': '#292D3E',
    'list.activeSelectionForeground': '#80CBC4',
    'list.inactiveSelectionForeground': '#80CBC4',
    'list.inactiveSelectionBackground': '#00000030',
    'list.focusBackground': '#A6ACCD20',
    'list.focusForeground': '#A6ACCD',
    'list.highlightForeground': '#80CBC4',
    'terminal.ansiWhite': '#ffffff',
    'terminal.ansiBlack': '#000000',
    'terminal.ansiBlue': '#82AAFF',
    'terminal.ansiCyan': '#89DDFF',
    'terminal.ansiGreen': '#C3E88D',
    'terminal.ansiMagenta': '#C792EA',
    'terminal.ansiRed': '#FF5370',
    'terminal.ansiYellow': '#FFCB6B',
    'terminal.ansiBrightWhite': '#ffffff',
    'terminal.ansiBrightBlack': '#676E95',
    'terminal.ansiBrightBlue': '#82AAFF',
    'terminal.ansiBrightCyan': '#89DDFF',
    'terminal.ansiBrightGreen': '#C3E88D',
    'terminal.ansiBrightMagenta': '#C792EA',
    'terminal.ansiBrightRed': '#FF5370',
    'terminal.ansiBrightYellow': '#FFCB6B',
    'terminalCursor.foreground': '#FFCB6B',
    'terminalCursor.background': '#000000',
    'scrollbarSlider.background': '#A6ACCD20',
    'scrollbarSlider.hoverBackground': '#A6ACCD10',
    'scrollbarSlider.activeBackground': '#80CBC4',
    'editorSuggestWidget.background': '#292D3E',
    'editorSuggestWidget.foreground': '#A6ACCD',
    'editorSuggestWidget.highlightForeground': '#80CBC4',
    'editorSuggestWidget.selectedBackground': '#00000050',
    'editorSuggestWidget.border': '#FFFFFF10',
    'editorWidget.background': '#292D3E',
    'editorWidget.resizeBorder': '#80CBC4',
    'editorWidget.border': '',
    'editorMarkerNavigation.background': '#A6ACCD05',
    'panel.border': '#292D3E60',
    'panel.background': '#292D3E',
    'panel.dropBackground': '#A6ACCD',
    'panelTitle.inactiveForeground': '#A6ACCD',
    'panelTitle.activeForeground': '#FFFFFF',
    'panelTitle.activeBorder': '#80CBC4',
    'diffEditor.insertedTextBackground': '#C3E88D15',
    'diffEditor.removedTextBackground': '#FF537020',
    'notifications.background': '#292D3E',
    'notifications.foreground': '#A6ACCD',
    'notificationLink.foreground': '#80CBC4',
    'badge.background': '#00000030',
    'badge.foreground': '#676E95',
    'extensionButton.prominentBackground': '#C3E88D90',
    'extensionButton.prominentHoverBackground': '#C3E88D',
    'peekView.border': '#00000030',
    'peekViewEditor.background': '#A6ACCD05',
    'peekViewTitle.background': '#A6ACCD05',
    'peekViewResult.background': '#A6ACCD05',
    'peekViewEditorGutter.background': '#A6ACCD05',
    'peekViewTitleDescription.foreground': '#A6ACCD60',
    'peekViewResult.matchHighlightBackground': '#717CB450',
    'peekViewEditor.matchHighlightBackground': '#717CB450',
    'gitDecoration.deletedResourceForeground': '#FF537090',
    'gitDecoration.conflictingResourceForeground': '#FFCB6B90',
    'gitDecoration.modifiedResourceForeground': '#82AAFF90',
    'gitDecoration.untrackedResourceForeground': '#C3E88D90',
    'gitDecoration.ignoredResourceForeground': '#676E9590',
    'peekViewResult.selectionBackground': '#676E9570',
    'breadcrumb.background': '#292D3E',
    'breadcrumb.foreground': '#676E95',
    'breadcrumb.focusForeground': '#A6ACCD',
    'breadcrumb.activeSelectionForeground': '#80CBC4',
    'breadcrumbPicker.background': '#292D3E',
    'menu.background': '#292D3E',
    'menu.foreground': '#A6ACCD',
    'menu.selectionBackground': '#00000050',
    'menu.selectionForeground': '#80CBC4',
    'menu.selectionBorder': '#00000030',
    'menu.separatorBackground': '#A6ACCD',
    'menubar.selectionBackground': '#00000030',
    'menubar.selectionForeground': '#80CBC4',
    'menubar.selectionBorder': '#00000030',
    'settings.dropdownForeground': '#A6ACCD',
    'settings.dropdownBackground': '#292D3E',
    'settings.numberInputForeground': '#A6ACCD',
    'settings.numberInputBackground': '#292D3E',
    'settings.textInputForeground': '#A6ACCD',
    'settings.textInputBackground': '#292D3E',
    'settings.headerForeground': '#80CBC4',
    'settings.modifiedItemIndicator': '#80CBC4',
    'settings.checkboxBackground': '#292D3E',
    'settings.checkboxForeground': '#A6ACCD',
    'listFilterWidget.background': '#00000030',
    'listFilterWidget.outline': '#00000030',
    'listFilterWidget.noMatchesOutline': '#00000030',
    'tree.indentGuidesStroke': '#4E5579',
  },
} as editor.IStandaloneThemeData;
